### ISSUE TITLE
Download image (not tiles)

### ISSUE THREAD

**Issue by DementevVV** [frogcat/petaviron#1]
Hi, is it possible to download a transformed image (without tiles)?
I tried to use `canvas.toDataURL` but in this case the picture is downloaded with an empty area around the picture (where was the map).

**Comment by frogcat** [comment]
OK, here I put working example to download transformed image when you click "save" button.
https://bl.ocks.org/frogcat/raw/b4172e63310e15e25681cd84994599b8/

Changes are here.
https://gist.github.com/frogcat/b4172e63310e15e25681cd84994599b8#file-script-js-L166-L172

Is this what you want?

**Comment by DementevVV** [comment]
> OK, here I put working example to download transformed image when you click "save" button.
> https://bl.ocks.org/frogcat/raw/b4172e63310e15e25681cd84994599b8/
> 
> Changes are here.
> https://gist.github.com/frogcat/b4172e63310e15e25681cd84994599b8#file-script-js-L166-L172
> 
> Is this what you want?

Yes, thank you!
